### ISSUE TITLE
Execution issue

### ISSUE THREAD

**Issue by usj94** [leangen/graphql-spqr-samples#3]
Hi,
I found u on Youtube and really amazing presentation that i need to clear Graphql concept.
 I've cloned this project and Tried to understand exactly what it is but when i executed this project i stuck for a moment because it is only showing Welcome to graphql-spqr-sample.. so i need ur help for Further Execution..

**Comment by BaldyLocks** [comment]
Hi,
this is the project used for the live demo on the presentations, we didn't really intend it for people to use as an example. However since a lot of people get confused by it I'll set aside some time in the next week to organize it and document it for external use. I'll post here when I do so you can give it a try again and see if you have any remaining questions.

If you don't want to wait here's a short explanation there are two controller classes, _GraphQlSampleController_ exposes two Graph QL endpoints (one exposes the example API mapped by using annotations the other one API generated through domain bean mappings) and _GraphiqlController_ is there to serve the Graphiql tool to try out the queries/mutations. 
To try out the queries go to one of the Graphiql urls mapped by _GraphiqlController_  and execute queries that are in the comments above query methods in _io.leangen.spqr.samples.demo.query_  package.

**Comment by BaldyLocks** [comment]
Added a brief readme, switched to using spring boot for easier deployment, updated comments, now only /graphql endpoint is exposed.
Bugs in Sangria version of graphiql ui client tool are still there, probably going to revert to the old version, less features but less buggy.

**Comment by string01** [comment]
Thx. I was going to redo that PR this week.
-d

**Comment by BaldyLocks** [comment]
No worries, it's been long coming to do it.

**Comment by usj94** [comment]
thnkx @BaldyLocks
